### PR TITLE
Fix changes variable overwrite

### LINKED ISSUE #2336: The horizontal scrollbar isn't updated properly after pasting text.
This issue is reproducible using the editor on http://ace.c9.io/#nav=about

Clear the text in the editor (ctrl+a and then backspace), and paste the following in it (including quotes):
"
SELECT ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, ATTRIBUTE16, ATTRIBUTE17, ATTRIBUTE18, ATTRIBUTE19
FROM TABLE1
"

A scrollbar does appear, but is not the correct scrollbar. After you use the scrollbar, it updates to a correct scrollbar. If you paste without the quotes, no scrollbar appears at all.
I've tested this in the following browsers:
-Chrome 40.0.2214.93 m
-FireFox 35.0
-IE 11.0.15

You can also see the issue below:

wrong scrollbar:
wrongscroll

the correct scrollbar that appears after scrolling:
correctscroll

### PR DESCRIPTION
**Pull request by souza-bruno**
*Issue #, if available:* Seems to fix #2336

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: lib/ace/virtual_renderer.js [hunk 1]
```diff
@@ -1061,7 +1061,7 @@ var VirtualRenderer = function(container, theme) {
         // Horizontal scrollbar visibility may have changed, which changes
         // the client height of the scroller
         if (hScrollChanged || vScrollChanged) {
-            changes = this.$updateCachedSize(true, this.gutterWidth, size.width, size.height);
+            changes += this.$updateCachedSize(true, this.gutterWidth, size.width, size.height);
```
Comment (nightwing) [inline lib/ace/virtual_renderer.js]: should this be `|=` instead?

Comment (souza-bruno) [reply lib/ace/virtual_renderer.js]: Yeah, it definitely should

**Comment by nightwing** [comment]
Thank you!
