### PR TITLE
Fixes an issue with Jade syntax highlighting

### LINKED ISSUE #2772: Incorrect JADE comments highlighting
JADE buffered comments in c9
jade-c9

For reference same code in some offline IDE
jade-webstorm

### PR DESCRIPTION
**Pull request by cifinn**
Fixes #2772 
Change to regex to allow Jade comments to be highlighted correctly.

### CODE REVIEW

**Comment by cifinn** [comment]
@nightwing hey was doing something silly but got the code and the tests working. Good to go

File: lib/ace/mode/jade_highlight_rules.js [hunk 1]
```diff
@@ -82,7 +82,7 @@ var JadeHighlightRules = function() {
         },
         {
             token : "punctuation.section.comment",
-            regex : "^\\s*\/\/(?:\\s*[^-\\s]|\\s+\\S)(?:.*$)"
+            regex : "^\\s*\/\/(?:\\s*[^\\s]|\\s+\\S)(?:.*$)"
```
Comment (nightwing) [inline lib/ace/mode/jade_highlight_rules.js]: Do you know if there are some characters not allowed in jade comments?
Seems like the whole `(?:\\s*[^\\s]|\\s+\\S)` part can be removed, simply leaving `"^\\s*//.*$"`.

**Comment by cifinn** [comment]
I'll investigate further to see if some characters are not allowed. If not, I'll alter it to your suggestion

**Comment by nightwing** [comment]
Merged, and made some further improvements in https://github.com/ajaxorg/ace/commit/021f41a81346cc7fd4de386d53206e608c5d9a5e
Thanks!

**Comment by cifinn** [comment]
@nightwing that looks great. This is a much cleaner solution
